USE PracticS1

BEGIN TRAN

--SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED -- dirty reads
SET TRANSACTION ISOLATION LEVEL READ COMMITTED -- fixes dirty reads

SELECT * FROM Tipografii

WAITFOR DELAY '00:00:04'

SELECT * FROM Tipografii

COMMIT TRAN