USE GradinaZoo

-- DIRTY READS
GO
CREATE OR ALTER PROCEDURE dirty_read_t1 AS
BEGIN
	BEGIN TRAN
	UPDATE Cusca SET capacitate = 55 WHERE cod_cusca = 1
	WAITFOR DELAY '00:00:05'
	ROLLBACK TRAN
END

GO
CREATE OR ALTER PROCEDURE dirty_read_t2 AS
BEGIN
	SET TRANSACTION ISOLATION LEVEL READ COMMITTED -- COMMITTED - fix

	BEGIN TRAN
	SELECT * FROM Cusca
	WAITFOR DELAY '00:00:10'
	SELECT * FROM Cusca

	COMMIT TRAN
END

GO
EXEC dirty_read_t1
EXEC dirty_read_t2 -- EXEC in different query


GO
CREATE OR ALTER PROCEDURE nr_reads_t1 AS
BEGIN
	BEGIN TRAN
	SELECT * FROM Cusca
	WAITFOR DELAY '00:00:10'
	SELECT * FROM Cusca

	COMMIT TRAN
END

GO
CREATE OR ALTER PROCEDURE nr_reads_t2 AS
BEGIN
	SET TRANSACTION ISOLATION LEVEL REPEATABLE READ -- REPEATABLE READ - fix

	BEGIN TRAN
	UPDATE Cusca SET capacitate = 60 WHERE cod_cusca = 1

	COMMIT TRAN
END

GO
EXEC nr_reads_t1
EXEC nr_reads_t2

UPDATE Cusca SET capacitate = 25 WHERE cod_cusca = 1


GO
CREATE OR ALTER PROCEDURE phantom_reads_t1 AS
BEGIN
	SET TRANSACTION ISOLATION LEVEL SERIALIZABLE  -- REPEATABLE READ - problem, SERIALIZABLE - fix
	BEGIN TRAN
	SELECT * FROM Cusca
	WAITFOR DELAY '00:00:10'
	SELECT * FROM Cusca
	COMMIT TRAN
END

GO
CREATE OR ALTER PROCEDURE phantom_reads_t2 AS
BEGIN
	BEGIN TRAN
	INSERT INTO Cusca VALUES ('delete', 20, 1)
	COMMIT TRAN
END

GO
EXEC phantom_reads_t1
EXEC phantom_reads_t2

DELETE FROM Cusca WHERE mediu = 'delete'


GO
CREATE OR ALTER PROCEDURE deadlock_t1 AS
BEGIN
	SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
	SET DEADLOCK_PRIORITY HIGH -- fix
	BEGIN TRAN
	UPDATE Cusca SET capacitate = 44 WHERE cod_cusca = 1
	WAITFOR DELAY '00:00:05'
	UPDATE Zona SET suprafata = 300 WHERE cod_zona = 1
	COMMIT TRAN
END

GO
CREATE OR ALTER PROCEDURE deadlock_t2 AS
BEGIN
	SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
	SET DEADLOCK_PRIORITY LOW -- fix
	BEGIN TRAN
	UPDATE Zona SET suprafata = 325 WHERE cod_zona = 1
	WAITFOR DELAY '00:00:05'
	UPDATE Cusca SET capacitate = 33 WHERE cod_cusca = 1
	COMMIT TRAN
END

GO
EXEC deadlock_t1
EXEC deadlock_t2
